apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "dshopBackendStorage.fullname" . }}"
  labels:
    app: {{ template "dshopBackendStorage.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dshop-backend
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: {{ template "dshopBackendStorage.fullname" . }}
 resources:
   requests:
     storage: {{ default "50Gi" .Values.dshopBackendStorageRequestSize }}
