apiVersion: v1
kind: Service
metadata:
  name: {{ template "dshopBackendRinkeby.fullname" . }}-balancer
  labels:
    app: {{ template "dshopBackendRinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dshop-backend-rinkeby
spec:
  type: LoadBalancer
  selector:
    app: {{ template "dshopBackendRinkeby.fullname" . }}
  ports:
  - name: http
    port: 3000
