apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dshopBackendRinkeby.fullname" . }}
  labels:
    app: {{ template "dshopBackendRinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dshop-backend-rinkeby
type: Opaque
data:
  ENCRYPTION_KEY: {{ required "Set a .Values.dshopBackendRinkebyEncryptionKey" .Values.dshopBackendRinkebyEncryptionKey | b64enc | quote}}
  SESSION_SECRET: {{ required "Set a .Values.dshopBackendRinkebySessionSecret" .Values.dshopBackendRinkebySessionSecret | b64enc | quote}}
  DATABASE_URL: {{ required "Set a .Values.dshopBackendRinkebyDatabaseURL" .Values.dshopBackendRinkebyDatabaseURL | b64enc | quote}}
  SENTRY_DSN: {{ required "Set a .Values.dshopBackendRinkebySentryDSN" .Values.dshopBackendRinkebySentryDSN | b64enc | quote}}
