apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "dshopBackendRinkeby.fullname" . }}
  labels:
    app: {{ template "dshopBackendRinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dshop-backend-rinkeby
spec:
  replicas: {{ default 2 .Values.dshopBackendRinkebyReplicas }}
  selector:
    matchLabels:
      app: {{ template "dshopBackendRinkeby.fullname" . }}
  serviceName: {{ template "dshopBackendRinkeby.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "dshopBackendRinkeby.fullname" . }}
    spec:
      containers:
      - name: dshop-backend-rinkeby
        image: "{{ .Values.containerRegistry }}/{{ .Release.Namespace }}/{{ .Values.dshopBackendRinkebyImage }}:{{ .Values.dshopBackendRinkebyImageTag }}"
        imagePullPolicy: Always
        env:
          - name: ENVIRONMENT
            value: "staging"
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "dshopBackendRinkeby.fullname" . }}
                key: ENCRYPTION_KEY
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "dshopBackendRinkeby.fullname" . }}
                key: SESSION_SECRET
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "dshopBackendRinkeby.fullname" . }}
                key: DATABASE_URL
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ template "dshopBackendRinkeby.fullname" . }}
                key: SENTRY_DSN
          - name: REDIS_URL
            value: "redis://{{ template "dshopRedisRinkeby.fullname" . }}-0.{{ template "dshopRedisRinkeby.fullname" . }}.experimental.svc.cluster.local:6379/0"
          - name: DSHOP_CACHE
            value: /data/dshop-cache/rinkeby
          - name: LOG_LEVEL
            value: {{ default "INFO" .Values.dshopBackendRinkebyLogLevel }}
          - name: EXTERNAL_IP
            value: {{ .Values.dshopIssuerRinkebyIp }}
        volumeMounts:
        - name: "{{ template "dshopBackendRinkeby.fullname" . }}-shared-cache"
          mountPath: /data/dshop-cache
        port:
          - name: http
            containerPort: 3000
        resources:
          requests:
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health/status
            port: 3000
          failureThreshold: 10
          periodSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/status
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3
        # Give Kubernetes time to do its thing (race error reduction)
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - "sleep 3"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.dshopBackendRinkebyDBInstance }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: dshop-cloudsql-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        # Don't kill DB connections before the backend process is terminated
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - "sleep 5"
      volumes:
        - name: dshop-cloudsql-credentials
          secret:
            secretName: dshop-cloudsql-credentials
        - name: "{{ template "dshopBackendRinkeby.fullname" . }}-shared-cache"
          persistentVolumeClaim:
            claimName: "{{ template "dshopBackendStorage.fullname" . }}"
            readOnly: false
