apiVersion: v1
kind: Service
metadata:
  name: {{ template "dshop-issuer-rinkeby.fullname" . }}
  labels:
    app: {{ template "dshop-issuer-rinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: dshop-backend-rinkeby
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.dshopIssuerRinkebyIp }}
  selector:
    app: {{ template "dshop-issuer-rinkeby.fullname" . }}
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
