apiVersion: v1
kind: Service
metadata:
  name: {{ template "dshopRedisRinkeby.fullname" . }}
  labels:
    app: {{ template "dshopRedisRinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dshop-backend-rinkeby
spec:
  clusterIP: None
  selector:
    app: {{ template "dshopRedisRinkeby.fullname" . }}
  ports:
  - name: redis
    port: 6379
  - name: gossip
    port: 16379
