apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "dshop-issuer-rinkeby.fullname" . }}
  labels:
    app: {{ template "dshop-issuer-rinkeby.fullname" . }}
    app.kubernetes.io/name: dshop
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: dshop-backend-rinkeby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "dshop-issuer-rinkeby.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "dshop-issuer-rinkeby.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: dshop-issuer-rinkeby
        image: "{{ .Values.containerRegistry }}/staging/{{ .Values.dshopIssuerImage }}:{{ .Values.dshopIssuerImageTag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: SERVER_ENDPOINT
            value: "{{ template "dshopBackendRinkeby.fullname" . }}-balancer.{{ .Release.Namespace }}.svc.cluster.local:3000"
            #value: "{{ template "dshopBackendRinkeby.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8080"
        volumeMounts:
          - name: {{ template "dshop-issuer-rinkeby.fullname" . }}-data
            mountPath: /etc/resty-auto-ssl
  volumeClaimTemplates:
  - metadata:
      name: {{ template "dshop-issuer-rinkeby.fullname" . }}-data
    spec:
      storageClassName: "standard"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
