containerRegistry: gcr.io/origin-214503

clusterIssuer: letsencrypt-prod

dshopBackendMainnetReplicas: 3
dshopBackendMainnetImage: dshop-backend
dshopBackendMainnetImageTag: mainnet

dshopBackendRinkebyReplicas: 2
dshopBackendRinkebyImage: dshop-backend
dshopBackendRinkebyImageTag: latest

dshopBackendStorageRequestSize: 1T

dshopRedisImage: redis
dshopRedisImageTag: 6.0

# dshop-issuer
dshopIssuerImage: origin-dapp-creator-issuer
dshopIssuerImageTag: latest
