apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ipfsCluster.fullname" . }}
  labels:
    app: {{ template "ipfsCluster.fullname" . }}
    app.kubernetes.io/name: origin
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ipfs-cluster
type: Opaque
data:
  CLUSTER_SECRET: {{ required "Set a .Values.ipfsClusterSecret" .Values.ipfsClusterSecret | b64enc | quote}}
  BOOTSTRAP_PEER_ID: {{ required "Set a .Values.ipfsBootstrapPeerID" .Values.ipfsBootstrapPeerID | b64enc | quote}}
  BOOTSTRAP_PEER_PRIV_KEY: {{ required "Set a .Values.ipfsBootstrapPrivkey" .Values.ipfsBootstrapPrivkey | b64enc | quote}}
  SHARED_SECRETS: {{ .Values.ipfsProxySharedSecrets | b64enc | quote}}
  BASIC_AUTH_PW: {{ .Values.ipfsProxyBasicAuthPassword | b64enc | quote}}
