databaseInstance: origin-214503:us-west1:dev

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: 'e3253c1'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '55a418e'

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '869699c'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: 'e05d00c'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '55a418e'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: 'b8cdfe7'

# origin-growth
growthImage: origin-growth
growthImageTag: '9c5edef'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: '9c7ebe9'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: 'f72819c'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: 'f2a9315'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '948b615'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.181.44'

# origin-cron
cronImage: origin-cron
cronImageTag: 'd4da76a'

# origin-admin
adminImage: origin-admin
adminImageTag: 'ff22671'

# origin-relayer
relayerImage: origin-relayer
relayerImageTag: '7de03d3'

# origin-graphql
graphqlImage: origin-graphql
graphqlImageTag: '55a418e'

# origin-token-transfer-client
t3ClientImage: origin-t3-client
t3ClientImageTag: 'cad1ce4'

# origin-token-transfer-server
t3ServerImage: origin-t3-server
t3ServerImageTag: '6f8cbeb'

# origin-auth
authImage: origin-auth
authImageTag: '2df1a66'

# origin-ipfs-issuer
ipfsIssuerIp: '35.185.244.158'
ipfsClusterIssuerIp: '34.105.56.194'
