databaseInstance: origin-214503:us-west1:staging

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '2aa3dbe'

# origin-dapp
dappImage: origin-dapp
dappImageTag: '7eb7ea0'

# origin-ipfs-proxy
ipfsProxyImage: origin-ipfs-proxy
ipfsProxyImageTag: '3393817'

# origin-faucet
faucetImage: origin-faucet
faucetImageTag: 'fac458a'

# event-listener
eventlistenerImage: event-listener
eventlistenerImageTag: '96f1a62'

# origin-discovery
discoveryImage: origin-discovery
discoveryImageTag: '01c08a5'

# origin-growth
growthImage: origin-growth
growthImageTag: 'a7ceead'

# origin-messaging
messagingImage: origin-messaging
messagingImageTag: '9c7ebe9'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: '67b8cd5'

# origin-dapp-creator-client
creatorClientImage: origin-dapp-creator-client
creatorClientImageTag: '1078040'

# origin-dapp-creator-server
creatorServerImage: origin-dapp-creator-server
creatorServerImageTag: '104d37f'

# origin-dapp-creator-issuer
creatorIssuerImage: origin-dapp-creator-issuer
creatorIssuerImageTag: 'latest'
creatorIssuerIp: '35.233.135.239'

# origin-linking
linkingImage: origin-linking
linkingImageTag: 'bce3090'

# origin-cron
cronImage: origin-cron
cronImageTag: '7d04c87'

# origin-admin
adminImage: origin-admin
adminImageTag: '5911970'

# origin-relayer
relayerImage: origin-relayer
relayerImageTag: '7ce7d9f'

# origin-graphql
graphqlImage: origin-graphql
graphqlImageTag: '96f1a62'

# origin-t3-client
t3ClientImage: origin-t3-client
t3ClientImageTag: '4716e54'

# origin-t3-server
t3ServerImage: origin-t3-server
t3ServerImageTag: 'df702a1'

# origin-auth
authImage: origin-auth
authImageTag: '7eb224a'

# origin-ipfs-issuer
ipfsIssuerIp: '35.230.9.58'
ipfsClusterIssuerIp: '34.105.25.179'
